Repository APPSCHOOL1-REPO/finalproject-gitspace, pull requests merged in 2023-07, with the labels that each got.

#452 [Feat] 앱 버전 체크 및 강제 업데이트 로직을 구현했습니다.
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/InitialView.swift
  GitSpace/Sources/Network/APIModels/AppInfo.swift
  GitSpace/Sources/Network/Services/AppStoreUpdateChecker.swift
Labels: ✨ Feature

#454 Feat/#453 hot fix text editor dark mode
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift
  GitSpace/Utilities/Extensions/View+TextEditorBackgroundColor.swift
Labels: 🔥HotFix

#455 Ver 1.0.1
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/InitialView.swift
  GitSpace/Sources/Network/APIModels/AppInfo.swift
  GitSpace/Sources/Network/Services/AppStoreUpdateChecker.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift
  GitSpace/Utilities/Extensions/View+TextEditorBackgroundColor.swift
Labels: ⌘ Buildup

#457 [Fix] 앱 버전 업데이트 가능 여부 검사 로직을 수정했습니다.
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Network/Services/AppStoreUpdateChecker.swift
  GitSpace/Utilities/Extensions/String+.swift
Labels: 🛠️ Fix

#458 Ver 1.0.1 #2
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Network/Services/AppStoreUpdateChecker.swift
  GitSpace/Utilities/Extensions/String+.swift
Labels: ⌘ Buildup

#444 Feat/#443 knock contents encryption
  GitSpace/Sources/ViewModels/KnockHistory/KnockViewManager.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/EachKnockCell.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift
  GitSpace/Sources/Views/Knock/SendKnock/AfterSendKnockSection.swift
  GitSpace/Sources/Views/Knock/SendKnock/SendKnockTextEditSection.swift
  GitSpace/Sources/Views/Knock/SendKnock/SendKnockView.swift
Labels: 🐛 Bug, ✨ Feature

#459 Feat/#442 simple encryption team
  GitSpace/Sources/Models/Chat.swift
  GitSpace/Sources/Models/Message.swift
  GitSpace/Sources/ViewModels/ChatViewModel.swift
  GitSpace/Sources/ViewModels/KnockHistory/KnockViewManager.swift
  GitSpace/Sources/ViewModels/MessageViewModel.swift
  GitSpace/Sources/ViewModels/TagViewModel.swift
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomKnockSection.swift
  GitSpace/Sources/Views/Home/AddTagSheetView.swift
  GitSpace/Sources/Views/Home/StarredView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/EachKnockCell.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift
  GitSpace/Sources/Views/Knock/SendKnock/AfterSendKnockSection.swift
  GitSpace/Sources/Views/Knock/SendKnock/SendKnockTextEditSection.swift
  GitSpace/Sources/Views/Knock/SendKnock/SendKnockView.swift
  GitSpace/Utilities/Extensions/String+.swift
Labels: ✨ Feature, 🛠️ Fix
