Repository APPSCHOOL1-REPO/finalproject-gitspace, pull requests merged in 2023-04, with the labels that each got.

#366 [Feat] 신고 모델을 추가하고 신고/차단 기능을 구현했습니다.
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Models/Report.swift
  GitSpace/Sources/Network/Interface/Blockable.swift
  GitSpace/Sources/Network/Interface/Reportable.swift
  GitSpace/Sources/ViewModels/UserViewModel.swift
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomInfoView.swift
  GitSpace/Utilities/Constant.swift
Labels: ✨ Feature

#371 [Feat] #367 차단/신고 뷰를 구현했습니다.
  GitSpace/Sources/Models/Report.swift
  GitSpace/Sources/Views/Common/BlockView.swift
  GitSpace/Sources/Views/Common/ReportView.swift
  GitSpace/Sources/Views/Common/SuggestBlockView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
  GitSpace/Utilities/CustomHostingController.swift
  GitSpace/Utilities/Extensions/View+.swift
  GitSpace/Utilities/HalfSheetManager.swift
Labels: ✨ Feature

#374 [Feat] 주체 사용자(subjectUser)가 객체 사용자(objectUser)를 차단했는지 검증하는 메서드를 구현했습니다.
  GitSpace/Sources/Network/Interface/Blockable.swift
Labels: ✨ Feature

#379 [Fix] 차단/차단제안 뷰의 텍스트 버튼 디자인을 변경했습니다.
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Views/Common/BlockView.swift
  GitSpace/Sources/Views/Common/SuggestBlockView.swift
Labels: 🎨 Design, 🛠️ Fix

#375 [Feat] 채팅방에서 상대방 메세지를 신고할 수 있는 기능을 추가했습니다.
  GitSpace/Sources/ViewModels/GitHubAuthManager.swift
  GitSpace/Sources/ViewModels/MessageViewModel.swift
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Sources/Views/Chat/ChatRoom/MessageCell.swift
Labels: ✨ Feature

#380 [Fix] ReportReasonDescription 열거형을 메서드로 변경했습니다.
  GitSpace/Sources/Models/Report.swift
  GitSpace/Sources/Views/Common/ReportView.swift
Labels: 🛠️ Fix

#382 [Feat] 차단 여부에 대한 채팅 기능 분기처리를 구현했습니다.
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Sources/Views/Knock/SendKnockView.swift
  GitSpace/Utilities/Components/GSTextEditor.swift
  GitSpace/Utilities/Constant.swift
  GitSpace/Utilities/Modifiers/GSTextEditorLayoutModifier.swift
Labels: ✨ Feature

#386 [Fix] 차단/차단제안 뷰의 텍스트 버튼을 다시 디자인했습니다.
  GitSpace/Sources/Views/Common/BlockView.swift
  GitSpace/Sources/Views/Common/SuggestBlockView.swift
Labels: 🛠️ Fix

#387 [Feat] TargetUserProfileView에서 차단 기능을 구현하고, 차단여부에 따라 뷰에 반영하였습니다.
  GitSpace/Sources/Views/Common/BlockView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: ✨ Feature

#389 [Feat] 채팅방에 차단 검사와 신고 Sheet를 연결했습니다.
  GitSpace/Sources/ViewModels/MessageViewModel.swift
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Sources/Views/Chat/ChatRoom/MessageCell.swift
Labels: ✨ Feature

#384 [Feat] Knock Message의 수정 업데이트와 ReportModal Trigger를 구현했습니다.
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Resources/Assets.xcassets/GSRed.colorset/Contents.json
  GitSpace/Sources/Router/KnockCommunicationRouter.swift
  GitSpace/Sources/ViewModels/KnockHistory/KnockViewManager.swift
  GitSpace/Sources/Views/Common/KnockMessageMenu.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift
  GitSpace/Sources/Views/Knock/SendKnockView.swift
  GitSpace/Utilities/Extensions/Color+.swift
Labels: ✨ Feature, 🛠️ Fix
