Repository APPSCHOOL1-REPO/finalproject-gitspace, pull requests merged in 2023-05, with the labels that each got.

#400 [Fix] 유저를 블락할 경우, 블락했다는 사실을 알 수 있도록 뷰를 리프레시 합니다.
  GitSpace/Sources/Views/Common/BlockView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: 🛠️ Fix

#401 [Fix] 깃스페이스 유저가 아닌 경우 TargetUserProfileView에서 신고 메뉴 버튼(Ellipsis)가 보이지 않도록 처리하였습니다.
  GitSpace/InitialView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: 🛠️ Fix

#402 [Feat] 신고 사유에 대한 설명(report reason description)을 작성했습니다.
  GitSpace/Sources/Models/Report.swift
Labels: 🎨 Design, 🛠️ Fix

#404 [Fix] Block Sheet가 종료되었을 때 Suggest Sheet가 사라지지 않는 현상을 수정했습니다.
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Sources/Views/Common/BlockView.swift
  GitSpace/Sources/Views/Common/ReportView.swift
  GitSpace/Sources/Views/Common/SuggestBlockView.swift
Labels: 🐛 Bug, 🛠️ Fix

#406 [Feat] 회원 탈퇴 시 로컬 데이터를 초기화하는 기능을 추가했습니다.
  GitSpace/Sources/ViewModels/ChatViewModel.swift
  GitSpace/Sources/ViewModels/KnockHistory/KnockViewManager.swift
  GitSpace/Sources/Views/Chat/MainChat/MainChatView.swift
  GitSpace/Sources/Views/Settings/Account/SetAccountView.swift
Labels: ✨ Feature

#407 Fix/#391, Fix/#390 knock profile image skeleton UI fix
  GitSpace/Sources/Models/UserInfo.swift
  GitSpace/Sources/Router/ContentView.swift
  GitSpace/Sources/ViewModels/UserViewModel.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/EachKnockCell.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift
  GitSpace/Utilities/Constant.swift
Labels: 🐛 Bug, ✨ Feature, 🛠️ Fix

#409 [Feat] 앱 내에 햅틱 피드백을 추가했습니다.
  GitSpace/Sources/Views/Settings/AppSettings/SetAppearanceView.swift
  GitSpace/Utilities/Components/GSTabBarIcon.swift
Labels: ✨ Feature

#410 Fix/#65 design system button implement disabled
  GitSpace/Resources/Assets.xcassets/GSGrayColors/GSgray1.colorset/Contents.json
  GitSpace/Sources/Views/Chat/MainChat/ChatUserRecommendationSection.swift
  GitSpace/Sources/Views/Common/TopperProfileView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
  GitSpace/Utilities/Components/GSButton.swift
  GitSpace/Utilities/Components/GSNavigationLink.swift
  GitSpace/Utilities/Constant.swift
  GitSpace/Utilities/Modifiers/GSButtonStyleModifiers.swift
  GitSpace/Utilities/Modifiers/LabelModifier.swift
  GitSpace/Utilities/ViewHighlightColorStyle.swift
Labels: 🛠️ Fix

#415 [Fix] #396 신고한 유저가 이미 차단한 유저일 경우, 차단제안뷰가 나오지 않도록 수정했습니다.
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Sources/Views/Common/ReportView.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift
  GitSpace/Sources/Views/Knock/SendKnockView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: 🛠️ Fix

#420 [Fix] Repository에 tag를 등록하고 다시 태그추가뷰로 가면 deselect 되어있는 버그를 고쳤습니다.
  GitSpace/Sources/ViewModels/TagViewModel.swift
  GitSpace/Sources/Views/Home/AddTagSheetView.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
  GitSpace/Sources/Views/Home/StarredView.swift
Labels: 🐛 Bug, 🛠️ Fix

#419 [Fix] 신고, 차단 로직의 toggle 호출을 정리합니다
  GitSpace/Sources/Views/Common/BlockView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: 🛠️ Fix

#418 [Fix] 신고/차단 Sheet 호출 방식을 사용하기 쉽도록 통합했습니다.
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Utilities/Extensions/View+.swift
Labels: 🛠️ Fix

#413 [Chore] BlockedUsers Class의 위치를 변경하고, BlockedUserList의 중복검사, 로그아웃/회원탈퇴 시 목록 비우기를 진행했습니다.
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Models/BlockedUsers.swift
  GitSpace/Sources/Network/Interface/Blockable.swift
  GitSpace/Sources/Views/Common/BlockView.swift
  GitSpace/Sources/Views/Settings/Account/SetAccountView.swift
Labels: 🛠️ Fix

#414 [Chore] SendKnockView를 리팩토링 했습니다.
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Router/KnockCommunicationRouter.swift
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomKnockSection.swift
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Sources/Views/Common/FailToLoadReadmeView.swift
  GitSpace/Sources/Views/Knock/SendKnock/AfterSendKnockSection.swift
  GitSpace/Sources/Views/Knock/SendKnock/BeforeSendKnockSection.swift
  GitSpace/Sources/Views/Knock/SendKnock/EditingKnockSection.swift
  GitSpace/Sources/Views/Knock/SendKnock/SendKnockTextEditSection.swift
  GitSpace/Sources/Views/Knock/SendKnock/SendKnockView.swift
  GitSpace/Sources/Views/Knock/SendKnockView.swift
  GitSpace/Sources/Views/Settings/Account/BlockedUsersListCell.swift
  GitSpace/Utilities/Extensions/View+.swift
Labels: 🛠️ Fix

#431 [Fix] GitSpace 유저 검증 로직을 수정하였습니다.
  GitSpace/Sources/Router/ContentView.swift
  GitSpace/Sources/Views/Home/ContributorListView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: 🛠️ Fix

#425 [Fix] View Profile → Chat/Knock View → View Profile의 무한 라우팅을 해결했습니다.
  GitSpace/Sources/Router/KnockCommunicationRouter.swift
  GitSpace/Sources/Views/Common/TopperProfileView.swift
  GitSpace/Sources/Views/Home/ContributorListView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: 🛠️ Fix

#430 [Feat] User Listener를 구현했습니다.
  GitSpace/Sources/Router/ContentView.swift
  GitSpace/Sources/ViewModels/ChatViewModel.swift
  GitSpace/Sources/ViewModels/UserViewModel.swift
Labels: ✨ Feature

#436 [Docs] Readmd 파일에 GitSpace 앱스토어 링크를 추가합니다.
  README.md
Labels: 📝 Documentation

#437 [Docs] Readmd 파일에 GitSpace 앱스토어 링크를 추가합니다.
  README.md
Labels: 📝 Documentation
