Repository APPSCHOOL1-REPO/finalproject-gitspace, pull requests merged in 2023-03, with the labels that each got.

#274 [Docs] Github RESTAPI 라이브러리 리스트에 추가
  README.md
Labels: 📝 Documentation

#278 Feat/#265 signin view loading yeseul
  GitSpace.xcodeproj/project.pbxproj
  GitSpace.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GitSpace/Resources/LoadingDots.json
  GitSpace/Resources/LoadingDotsDark.json
  GitSpace/Sources/Views/Auth/LoadingProgressView.swift
  GitSpace/Sources/Views/Auth/LottieView.swift
  GitSpace/Sources/Views/Auth/SigninView.swift
Labels: ✨ Feature

#280 Feat/#263 GitHub Auto Login 구현
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/InitialView.swift
  GitSpace/Sources/ViewModels/GitHubAuthManager.swift
  GitSpace/Sources/ViewModels/KeyChainManager.swift
  GitSpace/Sources/ViewModels/RepositoryViewModel.swift
  GitSpace/Sources/Views/Auth/SigninView.swift
Labels: ✨ Feature

#283 [Fix] Firestore DB UserInfo와 관련된 컬렉션과 필드명을 리터럴 값에서 Utility의 전역 상수로 교체합니다.
  GitSpace/Sources/Router/ContentView.swift
  GitSpace/Sources/ViewModels/GitHubAuthManager.swift
  GitSpace/Sources/ViewModels/MessageViewModel.swift
  GitSpace/Sources/ViewModels/RepositoryViewModel.swift
  GitSpace/Sources/ViewModels/TagViewModel.swift
  GitSpace/Sources/ViewModels/UserViewModel.swift
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Utilities/Constant.swift
Labels: 🛠️ Fix

#284 #281 sign in view auto login loading yeseul
  GitSpace/InitialView.swift
  GitSpace/Sources/ViewModels/GitHubAuthManager.swift
  GitSpace/Sources/Views/Auth/SigninView.swift
Labels: ✨ Feature, 🛠️ Fix

#288 Design/#287 gs text editor color taeyoung
  GitSpace.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GitSpace/Sources/ViewModels/GitHubAuthManager.swift
  GitSpace/Utilities/Components/GSTextField.swift
  GitSpace/Utilities/Modifiers/GSTextFieldLayoutModifier.swift
Labels: 🎨 Design, 🛠️ Fix

#290 Fix/#268 repository detail view contributor list jegyun
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Network/Common/GitHubAPIError.swift
  GitSpace/Sources/Network/Common/HTTPClient.swift
  GitSpace/Sources/ViewModels/ContributorViewModel.swift
  GitSpace/Sources/ViewModels/RepositoryDetailViewModel.swift
  GitSpace/Sources/ViewModels/UserProfileViewModel.swift
  GitSpace/Sources/Views/Home/ContributorListSkeletonCell.swift
  GitSpace/Sources/Views/Home/MainHomeView.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
  GitSpace/Sources/Views/Home/StarredView.swift
  GitSpace/Sources/Views/Profile/UserProfileView.swift
Labels: 🛠️ Fix

#292 Feat/#291 ContirbutorListView-MoveToProfile-hanho
  GitSpace/Sources/Views/Home/ContributorListCell.swift
  GitSpace/Sources/Views/Home/ContributorListView.swift
Labels: ✨ Feature, 🛠️ Fix

#294 [Chore] #289 채팅 갯수가 0개일 때 ChatListSection에 empty view를 띄워주도록 코드 추가.
  GitSpace/Sources/Views/Chat/MainChat/ChatListSection.swift
Labels: ✨ Feature

#300 [Fix] #299 Contributors가 불러와지는 동안(.isLoading) ContributorListView에 진입할 경우, View가 깨지는 현상을 수정했습니다.
  GitSpace/Sources/ViewModels/ContributorViewModel.swift
  GitSpace/Sources/Views/Home/ContributorListView.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
Labels: 🛠️ Fix

#304 [Fix] #301 zombie user 문제를 해결했습니다. (임시방편)
  GitSpace/InitialView.swift
Labels: 🐛 Bug, 🛠️ Fix

#306 [Chore] #305 StarredView의 검색창을 주석처리하고, 필요한 코드들을 정리합니다.
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-AddTagSheetView.imageset/Contents.json
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-AddTagSheetView.imageset/emptyView-tag-dark.png
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-AddTagSheetView.imageset/emptyView-tag-dark@2x.png
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-AddTagSheetView.imageset/emptyView-tag-dark@3x.png
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-AddTagSheetView.imageset/emptyView-tag-light.png
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-AddTagSheetView.imageset/emptyView-tag-light@2x.png
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-AddTagSheetView.imageset/emptyView-tag-light@3x.png
  GitSpace/Sources/ViewModels/GitHubAuthManager.swift
  GitSpace/Sources/ViewModels/RepositoryViewModel.swift
  GitSpace/Sources/Views/Auth/SigninView.swift
  GitSpace/Sources/Views/Home/AddTagSheetView.swift
  GitSpace/Sources/Views/Home/StarredView.swift
  GitSpace/Utilities/Constant.swift
Labels: 🎨 Design, ⌘ Buildup, 🛠️ Fix

#307 [Feat / Chore] #303 SendKnockView | 최초 릴리즈 버전에 맞게 뷰를 수정했습니다.
  GitSpace/Sources/Views/Knock/SendKnockView.swift
Labels: ✨ Feature, 🛠️ Fix

#309 [Chore] 출시 버전에 맞춰서 사용하지 않은 Chat View의 컴포넌트들을 숨김 처리 했습니다.
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
Labels: 🛠️ Fix

#311 Fix/#271 user profile view jegyun, Closes #271
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Network/APIModels/FollowerResponse.swift
  GitSpace/Sources/Network/Common/HTTPClient.swift
  GitSpace/Sources/Network/Endpoints/GitHubAPIEndpoint.swift
  GitSpace/Sources/Network/Services/GitHubService.swift
  GitSpace/Sources/Router/ContentView.swift
  GitSpace/Sources/ViewModels/FollowerViewModel.swift
  GitSpace/Sources/ViewModels/TargetUserProfileViewModel.swift
  GitSpace/Sources/Views/Chat/ChatRoom/MessageCell.swift
  GitSpace/Sources/Views/Common/FailToLoadReadmeView.swift
  GitSpace/Sources/Views/Common/ReadmeLoadingView.swift
  GitSpace/Sources/Views/Common/TopperProfileView.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
  GitSpace/Sources/Views/Knock/SendKnockView.swift
  GitSpace/Sources/Views/Notification/KnockNotificationCell.swift
  GitSpace/Sources/Views/Profile/CurrentUserProfileView.swift
  GitSpace/Sources/Views/Profile/MainProfileView.swift
  GitSpace/Sources/Views/Profile/ProfileDetailView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
  GitSpace/Utilities/Components/GSCanvas.swift
Labels: 🐛 Bug, ✨ Feature, 🛠️ Fix

#314 Fix/#271 user profile view jegyun, Closes #271
  GitSpace/Sources/Views/Profile/CurrentUserProfileView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: 🐛 Bug, ✨ Feature, 🛠️ Fix

#316 Fix/#271 user profile view jegyun, Closes #271
  GitSpace.xcodeproj/project.pbxproj
Labels: 🐛 Bug, ✨ Feature, 🛠️ Fix

#321 [Feat] 노크를 수락하면 신규 채팅방을 개설하고 Chat 탭으로 라우팅하는 기능을 구현합니다.
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Models/Chat.swift
  GitSpace/Sources/ViewModels/ChatViewModel.swift
  GitSpace/Sources/ViewModels/UserViewModel.swift
  GitSpace/Sources/Views/Chat/MainChat/AddChatView.swift
  GitSpace/Sources/Views/Chat/MainChat/ChatListCell.swift
  GitSpace/Sources/Views/Chat/MainChat/ChatListSection.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift
Labels: ✨ Feature

#323 Feat/#298 knock view manager check if knock has been sent
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Models/Knock.swift
  GitSpace/Sources/Router/KnockCommunicationRouter.swift
  GitSpace/Sources/ViewModels/KnockHistory/KnockViewManager.swift
  GitSpace/Sources/Views/Chat/MainChat/AddChatView.swift
  GitSpace/Sources/Views/Home/ContributorListView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift
Labels: ✨ Feature

#319 Closes #271 UserProfileView
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Network/APIModels/FollowerResponse.swift
  GitSpace/Sources/Network/Common/HTTPClient.swift
  GitSpace/Sources/Network/Endpoints/GitHubAPIEndpoint.swift
  GitSpace/Sources/Network/Services/GitHubService.swift
  GitSpace/Sources/ViewModels/FollowerViewModel.swift
  GitSpace/Sources/ViewModels/TargetUserProfileViewModel.swift
  GitSpace/Sources/Views/Chat/ChatRoom/MessageCell.swift
  GitSpace/Sources/Views/Common/FailToLoadReadmeView.swift
  GitSpace/Sources/Views/Common/ReadmeLoadingView.swift
  GitSpace/Sources/Views/Common/TopperProfileView.swift
  GitSpace/Sources/Views/Home/ContributorListCell.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
  GitSpace/Sources/Views/Home/StarredView.swift
  GitSpace/Sources/Views/Knock/SendKnockView.swift
  GitSpace/Sources/Views/Notification/KnockNotificationCell.swift
  GitSpace/Sources/Views/Profile/CurrentUserProfileView.swift
  GitSpace/Sources/Views/Profile/MainProfileView.swift
  GitSpace/Sources/Views/Profile/ProfileDetailView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
  GitSpace/Sources/Views/Profile/UserProfileView.swift
  GitSpace/Utilities/Components/GSCanvas.swift
Labels: 🐛 Bug, ✨ Feature, 🛠️ Fix

#312 Fix/#295 dark mode design check yeseul
  GitSpace/Sources/Views/Home/AddTagSheetView.swift
  GitSpace/Sources/Views/Home/MainHomeView.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
  GitSpace/Sources/Views/Knock/KnockBox/ReceivedKnockView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift
  GitSpace/Utilities/Components/GSText.swift
  GitSpace/Utilities/Constant.swift
Labels: ✨ Feature, 🛠️ Fix

#328 Fix/#317 add missing files jegyun
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Router/ContentView.swift
  GitSpace/Sources/ViewModels/CurrentUserProfileViewModel.swift
  GitSpace/Sources/Views/Profile/CurrentUserProfileView.swift
Labels: 🛠️ Fix

#330 [Feat] GSTextEditor 디자인 시스템에 메세지 전송 가능 유효성 검사 체크 로직을 추가했습니다.
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Sources/Views/Knock/SendKnockView.swift
  GitSpace/Utilities/Components/GSTextEditor.swift
Labels: ✨ Feature, 🎨 Design

#332 [Add] #259 Tagging에서 삭제 기능을 추가했습니다.
  GitSpace/Sources/ViewModels/TagViewModel.swift
  GitSpace/Sources/Views/Home/AddTagSheetView.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
  GitSpace/Sources/Views/Home/StarredView.swift
Labels: ✨ Feature, 🛠️ Fix

#334 [Fix] #333 다른 사용자들의 Tag가 공유되는 Bug를 수정하였습니다.
  GitSpace/Sources/ViewModels/TagViewModel.swift
  GitSpace/Utilities/Constant.swift
Labels: 🔥HotFix

#336 Fix/#325 push notification wrong user name
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Models/PushNotification/PushNotificationManager.swift
  GitSpace/Sources/Models/PushNotification/PushNotificationMessageBody.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/EachKnockCell.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/MainKnockView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift
  GitSpace/Sources/Views/Knock/SendKnockView.swift
Labels: 🛠️ Fix

#340 [Feat] #327 TargetUser의 Following과 Followers List를 호출하는 함수를 구현하고 적용합니다.
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/GitSpaceApp.swift
  GitSpace/Sources/Network/APIModels/FollowingResponse.swift
  GitSpace/Sources/Network/Endpoints/GitHubAPIEndpoint.swift
  GitSpace/Sources/Network/Services/GitHubService.swift
  GitSpace/Sources/ViewModels/FollowerViewModel.swift
  GitSpace/Sources/Views/Chat/MainChat/ChatUserRecommendationSection.swift
  GitSpace/Sources/Views/Chat/MainChat/MainChatView.swift
  GitSpace/Sources/Views/Profile/CurrentUserProfileView.swift
  GitSpace/Sources/Views/Profile/FollowingSkeletonView.swift
  GitSpace/Sources/Views/Profile/TargetUserFollowingListView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: ✨ Feature

#342 Fix/#295 dark mode setting yeseul
  GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: 🛠️ Fix

#345 [Feat] #344 LicensesView에 콘텐츠를 추가하였습니다.
  GitSpace/Sources/Views/Settings/Legal/SetLicensesView.swift
  GitSpace/Sources/Views/Settings/SetMainView.swift
Labels: ✨ Feature

#347 [Chore] #346 ReadMe 로딩 실패 및 ReadMe가 없을 경우를 분기 처리하여 해당 경우에 맞는 뷰를 띄워주도록 수정하였습니다.
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-ReadMe-Empty.imageset/Contents.json
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-ReadMe-Empty.imageset/GitSpace-Readme-Empty-Dark.png
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-ReadMe-Empty.imageset/GitSpace-Readme-Empty-Dark@2x.png
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-ReadMe-Empty.imageset/GitSpace-Readme-Empty-Dark@3x.png
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-ReadMe-Empty.imageset/GitSpace-Readme-Empty.png
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-ReadMe-Empty.imageset/GitSpace-Readme-Empty@2x.png
  GitSpace/Resources/Assets.xcassets/MascotImages/EmptyView/GitSpace-ReadMe-Empty.imageset/GitSpace-Readme-Empty@3x.png
  GitSpace/Sources/ViewModels/ContributorViewModel.swift
  GitSpace/Sources/ViewModels/CurrentUserProfileViewModel.swift
  GitSpace/Sources/ViewModels/RepositoryDetailViewModel.swift
  GitSpace/Sources/ViewModels/TargetUserProfileViewModel.swift
  GitSpace/Sources/Views/Common/FailToLoadReadmeView.swift
  GitSpace/Sources/Views/Common/ReadmeLoadingView.swift
  GitSpace/Sources/Views/Home/ContributorListSkeletonCell.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
  GitSpace/Sources/Views/Profile/CurrentUserProfileView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
Labels: ✨ Feature, 🛠️ Fix

#337 Update README.md
  README.md
Labels: 📝 Documentation

#348 Fix/#65 design system button style update
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  GitSpace/Resources/Assets.xcassets/GSPurple.colorset/Contents.json
  GitSpace/Resources/Assets.xcassets/GSRed.colorset/Contents.json
  GitSpace/Sources/Views/Home/AddTagSheetView.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
  GitSpace/Sources/Views/Home/StarredView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/EachKnockCell.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/MainKnockView.swift
  GitSpace/Utilities/Components/GSButton.swift
  GitSpace/Utilities/Components/GSNavigationLink.swift
  GitSpace/Utilities/Constant.swift
  GitSpace/Utilities/DesignSystemStyleEnums.swift
  GitSpace/Utilities/Extensions/Button+ColorScheme.swift
  GitSpace/Utilities/Extensions/View+DesignSystem.swift
  GitSpace/Utilities/Modifiers/ColorSchemeModifiers.swift
  GitSpace/Utilities/Modifiers/GSButonStyleModifiers.swift
  GitSpace/Utilities/Modifiers/LabelModifier.swift
Labels: ✨ Feature, 🎨 Design, 🛠️ Fix

#352 Feat/#351 push notification setting
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Sources/Models/PushNotification/PushNotificationManager.swift
  GitSpace/Sources/Models/PushNotification/PushNotificationMessageBody.swift
  GitSpace/Sources/Models/UserInfo.swift
  GitSpace/Sources/Router/ContentView.swift
  GitSpace/Sources/ViewModels/UserViewModel.swift
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Sources/Views/Home/RepositoryDetailView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/EachKnockCell.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/MainKnockView.swift
  GitSpace/Sources/Views/Settings/AppSettings/SetNotificationsView.swift
  GitSpace/Sources/Views/Settings/SetMainView.swift
  GitSpace/Utilities/Constant.swift
  GitSpace/Utilities/Extensions/AppDelegate+Firebase.swift
  GitSpace/Utilities/Extensions/Button+ColorScheme.swift
  GitSpace/Utilities/Extensions/View+DesignSystem.swift
  GitSpace/Utilities/Modifiers/GSButtonStyleModifiers.swift
Labels: ✨ Feature, 🛠️ Fix

#356 [Chore] #355 Settings > Blocked Users를 비활성화 했습니다.
  GitSpace/Sources/Views/Settings/SetAccountView.swift
Labels: 🛠️ Fix

#358 [HotFix] 신규 유저정보 등록 시 deviceToken 필드가 정상적으로 반영되지 않는 문제를 해결했습니다.
  .gitignore
  GitSpace/Resources/App/plist/GoogleService-Info.plist
  GitSpace/Resources/App/plist/Info.plist
  GitSpace/Sources/ViewModels/GitHubAuthManager.swift
  GitSpace/Sources/ViewModels/UserViewModel.swift
Labels: 🔥HotFix

#359 [Feat] 채팅방 입장 스크롤링을 최적화합니다.
  GitSpace/Sources/ViewModels/MessageViewModel.swift
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
Labels: ✨ Feature

#362 [HotFix] 릴리즈 버전의 버그를 수정합니다.
  .gitignore
  GitSpace.xcodeproj/project.pbxproj
  GitSpace/Resources/App/plist/GoogleService-Info.plist
  GitSpace/Resources/App/plist/Info.plist
  GitSpace/Sources/Router/ContentView.swift
  GitSpace/Sources/ViewModels/GitHubAuthManager.swift
  GitSpace/Sources/ViewModels/MessageViewModel.swift
  GitSpace/Sources/ViewModels/UserViewModel.swift
  GitSpace/Sources/Views/Auth/SigninView.swift
  GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
  GitSpace/Sources/Views/Chat/MainChat/AddChatView.swift
  GitSpace/Sources/Views/Home/ActivityFeedView.swift
  GitSpace/Sources/Views/Home/ContributorListView.swift
  GitSpace/Sources/Views/Home/MainHomeView.swift
  GitSpace/Sources/Views/Home/StarredView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/MainKnockView.swift
  GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift
  GitSpace/Sources/Views/Knock/SendKnockView.swift
  GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
  GitSpace/Sources/Views/Settings/Legal/TermsOfServiceView.swift
  GitSpace/Sources/Views/Settings/SetMainView.swift
  GitSpace/Utilities/Components/GSButton.swift
  GitSpace/Utilities/Components/GSTextField.swift
Labels: 🔥HotFix
